### ISSUE TITLE
Error when starting the program

### ISSUE THREAD

**Issue by David-Valters** [Curovearth/Are-you-Drowsy#1]
Traceback (most recent call last):
  File "/home/dio/project/Are-you-Drowsy/main_drowsy.py", line 5, in <module>
    import dlib
  File "/home/dio/.local/lib/python3.10/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: /home/dio/.local/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-x86_64-linux-gnu.so: undefined symbol: cblas_dtrsm

`pip show dlib`
Name: dlib
Version: 19.24.0
Summary: A toolkit for making real world machine learning and data analysis applications
Home-page: https://github.com/davisking/dlib
Author: Davis King
Author-email: davis@dlib.net
License: Boost Software License
Location: /home/dio/.local/lib/python3.10/site-packages

OS: OS: Manjaro Linux x86_64

**Comment by Curovearth** [comment]
Hi, I apologize for such long time without giving any response. It was skipped from my notifications. 
I am not sure about the error for now. Could you try **downgrading your dlib version** and see if that helps you or not.

If I get to know some other helpful response, I'll update it here. Apologies for the inconvenience.

**Comment by Mashhur0108** [comment]
Hi. I have a problem dlib library is not working
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

**Comment by Curovearth** [comment]
@Mashhur0108 Is it prompting you to install `cmake`? 
The resources which I have found online (I am assuming you must have gone through it) suggests users to install cmake and then reinstall dlib.
